name: mataresit_app
description: "Mataresit - Receipt Management Flutter App"
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Navigation
  go_router: ^16.2.1

  # Backend & Database
  supabase_flutter: ^2.8.2

  # Image Processing & File Handling
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  image: ^4.2.0
  file_picker: ^10.3.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  
  # Local Storage & Offline Sync
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.0

  # Push Notifications & Real-time
  flutter_local_notifications: ^19.4.1

  # Security & Biometrics
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  otp: ^3.1.4
  qr_flutter: ^4.1.0
  sign_in_with_apple: ^6.1.2

  # Performance & Background Processing
  workmanager: ^0.9.0

  # UI Components
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  
  # AI & Analytics
  google_generative_ai: ^0.4.6
  fl_chart: ^1.1.0

  # Utilities
  logger: ^2.4.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  timeago: ^3.7.0
  path: ^1.9.0
  http: ^1.2.2
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0

  # Internationalization
  easy_localization: ^3.0.7

  # Export & File Sharing
  pdf: ^3.11.1
  excel: ^4.0.6
  csv: ^6.0.0
  share_plus: ^10.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - .env
